#!/usr/bin/php
<?php

require_once __DIR__ . '/bootstrap.php';

if(php_sapi_name() !== 'cli'){
    exit('only cli interface');
}
set_time_limit(0);
$consoleApp = new \App\Console\Kernel();
$consoleApp->run();

?>